/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ageregister.view;

import ageregister.Container;
import ageregister.DBHandler;
import ageregister.FetchData;
import ageregister.FetchFilteredData;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oshan
 */
public class AddData extends javax.swing.JFrame {

    
   DefaultTableModel m1,m_main;
   FetchFilteredData ffd=new FetchFilteredData();
   FetchData fd=new FetchData();
   ViewAll va=new ViewAll();
   
    Set<String> s;
  //  String[] suggestios={"Uda Julampitiya","Palle Julampitiya","Galwadiya","Julampitiya","Muruthawela Ihala","Muruthawela Pahala",""};
   
    /**
     * Creates new form AddData
     */
    public AddData() {
        initComponents();
        
//        s=new TreeSet<String>();
//        for(int x=0;x<suggestios.length;x++){
//        s.add(suggestios[x]);}
//        
    }
    
    public AddData(DefaultTableModel m_main,DefaultTableModel m,ViewAll va) {
        initComponents();
        this.m1=m;
        this.m_main=m_main;
        this.va=va;
        
//        s=new TreeSet<String>();
//        for(int x=0;x<suggestios.length;x++){
//        s.add(suggestios[x]);}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtcontactno = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtbirthday = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Records");
        setLocation(new java.awt.Point(500, 110));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcontactno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcontactno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 3, true));
        txtcontactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontactnoActionPerformed(evt);
            }
        });
        txtcontactno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcontactnoKeyPressed(evt);
            }
        });
        jPanel1.add(txtcontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 200, 32));

        txtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 3, true));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 560, 32));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setMaximumRowCount(20);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Unknown", "Sri Saddananda Piriwena Omara", "Walasmulla National School", "Warapitiya Secondary School", "Hadugala M.V", "Horewela M.V", "Kirama Dammananda M.V", "Medagamgoda M.V", "Omara M.V", "Egodabedda M.V", "Radaniara M.V", "Muruthawela M.V", "Pallejulampitiya M.V", "Kekiriobada M.V", "Vidikanda K.V", "Thalapathkanda K.V", "Keredeniya K.V", "Konkarahena K.V", "Bowala K.V", "Galwadiya K.V", "Agalabada K.V", "Bowala Vidyalaya" }));
        jComboBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 3, true));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 200, 30));

        txtbirthday.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtbirthday.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 3, true));
        txtbirthday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbirthdayKeyPressed(evt);
            }
        });
        jPanel1.add(txtbirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 200, 32));

        txtaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtaddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 3, true));
        txtaddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaddressKeyPressed(evt);
            }
        });
        jPanel1.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 560, 32));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Age supervising system");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 180, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BirthDay(y-m-d)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact Number");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("School");

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 190, 340));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ageregister/view/t22.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 570));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 590, 152, 38));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 152, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtcontactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontactnoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Container cnt=new Container();
        DBHandler db=new DBHandler();
    try{    
       String[] a=txtbirthday.getText().split("-");
       if((txtcontactno.getText().length()!=10)){ 
           JOptionPane.showMessageDialog(this, "Please check again the contact number , you entered. It should contain 10 digits!");
       }
       else if(jComboBox1.getSelectedIndex()==0){JOptionPane.showMessageDialog(this,"Please select the GN Division to continue!");}
       else if((Integer.parseInt(a[2])>31) ||(Integer.parseInt(a[1])>12 ) ||(a[0].length()!=4)){
           JOptionPane.showMessageDialog(this,"Please check again the numbers in birthday, you entered!");
       }
       else{
           cnt.setName(txtname.getText());
           //cnt.setGNdiv(txtGND.getText());
           cnt.setGNdiv(jComboBox1.getSelectedItem().toString());
           cnt.setAddress(txtaddress.getText());
           cnt.setContact(txtcontactno.getText());
           cnt.setBirthday(txtbirthday.getText());
           
           if(db.addData(cnt)){
              txtname.setText("");
              jComboBox1.setSelectedIndex(0);
              txtaddress.setText("");
              txtcontactno.setText("");
              txtbirthday.setText("");
              JOptionPane.showMessageDialog(this, "Successfully Added!");
           }
           else{
               JOptionPane.showMessageDialog(this, "Something Went Wrong!");
           }
            }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(this, "Please check again the birthday, you entered ! \n eg:   2000-5-12");
    }
//        m1.setRowCount(0);
//        ffd.getAndFilterData(new Date(), m1);
         m1.setRowCount(0);
            fd.getData(m1,va);
            m_main.setRowCount(0);
            ffd.getAndFilterData(new Date(), m_main);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed

    }//GEN-LAST:event_txtnameKeyPressed

    private void txtaddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaddressKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
             txtcontactno.requestFocusInWindow();
         }

    }//GEN-LAST:event_txtaddressKeyPressed

    private void txtcontactnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontactnoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
             txtbirthday.requestFocusInWindow();
         }

    }//GEN-LAST:event_txtcontactnoKeyPressed

    private void txtbirthdayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbirthdayKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
             Container cnt=new Container();
        DBHandler db=new DBHandler();
    try{    
       String[] a=txtbirthday.getText().split("-");
       if((txtcontactno.getText().length()!=10)){ 
           JOptionPane.showMessageDialog(this, "Please check again the contact number , you entered. It should contain 10 digits!");
       }
       else if(jComboBox1.getSelectedIndex()==0){JOptionPane.showMessageDialog(this,"Please select the GN Division to continue!");}
       else if((Integer.parseInt(a[2])>31) ||(Integer.parseInt(a[1])>12 ) ||(a[0].length()!=4)){
           JOptionPane.showMessageDialog(this,"Please check again the numbers in birthday, you entered!");
       }
       else{
           cnt.setName(txtname.getText());
           //cnt.setGNdiv(txtGND.getText());
           cnt.setGNdiv(jComboBox1.getSelectedItem().toString());
           cnt.setAddress(txtaddress.getText());
           cnt.setContact(txtcontactno.getText());
           cnt.setBirthday(txtbirthday.getText());
           
           if(db.addData(cnt)){
              txtname.setText("");
              jComboBox1.setSelectedIndex(0);
              txtaddress.setText("");
              txtcontactno.setText("");
              txtbirthday.setText("");
              JOptionPane.showMessageDialog(this, "Successfully Added!");
           }
           else{
               JOptionPane.showMessageDialog(this, "Something Went Wrong!");
           }
            }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(this, "Please check again the birthday, you entered ! \n eg:   2000-5-12");
    }
//        m1.setRowCount(0);
//        ffd.getAndFilterData(new Date(), m1);
         m1.setRowCount(0);
            fd.getData(m1,va);
            m_main.setRowCount(0);
            ffd.getAndFilterData(new Date(), m_main);
         }
    }//GEN-LAST:event_txtbirthdayKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtbirthday;
    private javax.swing.JTextField txtcontactno;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
