/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ageregister.view;


import ageregister.AgeCalculator;
import ageregister.DBHandler;
import ageregister.FetchData;
import ageregister.FetchFilteredData;
import ageregister.FinalizedDataHandler;

import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


import javax.swing.table.DefaultTableModel;

import javax.swing.table.TableColumnModel;

/**
 *
 * @author Oshan
 */
public class ViewAll extends javax.swing.JFrame {

    FetchData fd=new FetchData();
    FetchFilteredData ffd=new FetchFilteredData();
    DBHandler db=new DBHandler();
    AgeCalculator agct=new AgeCalculator(new Date());
    FinalizedDataHandler fdh=new FinalizedDataHandler();
 
    
    /**
     * Creates new form ViewAll
     */
    DefaultTableModel m,m_main;
    public ViewAll() {
        initComponents();
        
    }
    public ViewAll(DefaultTableModel m2){
        initComponents();
        m=(DefaultTableModel)jTable1.getModel();
        this.m_main=m2;
        
        TableColumnModel tcm=jTable1.getColumnModel();
        tcm.removeColumn(tcm.getColumn(0));
        tcm.getColumn(0).setPreferredWidth(180);//name
       // tcm.getColumn(1).setPreferredWidth(60);
        tcm.getColumn(2).setPreferredWidth(300);//address
        tcm.getColumn(3).setPreferredWidth(60);//contact no
        tcm.getColumn(4).setPreferredWidth(50);//birthday
        tcm.getColumn(5).setPreferredWidth(40);
        tcm.getColumn(6).setPreferredWidth(65);
        
        fd.getData(m,this);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_marked1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public String getToolTipText(MouseEvent e){
                String tip=null;
                java.awt.Point p=e.getPoint();
                int rowIndex=rowAtPoint(p);

                try{
                    tip=agct.getAgeUpToDate(getValueAt(rowIndex, 4).toString());

                }
                catch(RuntimeException e1){
                    e1.printStackTrace();
                }
                return tip;
            }};
            jPanel2 = new javax.swing.JPanel();
            jButton4 = new javax.swing.JButton();
            jButton3 = new javax.swing.JButton();
            jButton5 = new javax.swing.JButton();
            jPanel4 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            txtSearchBar = new javax.swing.JTextField();
            btnSearch = new javax.swing.JButton();
            jPanel5 = new javax.swing.JPanel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jComboBox_marked = new javax.swing.JComboBox<>();
            jButton1 = new javax.swing.JButton();
            jButton6 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();
            jButton9 = new javax.swing.JButton();
            jLabel4 = new javax.swing.JLabel();
            jComboBox_all = new javax.swing.JComboBox<>();

            jComboBox_marked1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jComboBox_marked1.setMaximumRowCount(16);
            jComboBox_marked1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Agalabada", "Batagassa", "Bowala Uthura", "Bowala Dakuna", "Bowala Batahira", "Daluwakgoda", "Dehigahahena", "Egodabedda", "Ethpitiya", "Galahitiya Uthura", "Galahitiya Dakuna", "Galahitiya Negenahira", "Galwadiya", "Hadugala", "Horewela", "Julampitiya", "Kebellaketiya", "Kekiriobada", "Keredeniya", "Koholana", "Koonkarahena", "Mapitakanda", "Mathuwakanda", "Medagamgoda", "Muruthawela Ihala", "Muruthawela Pahala", "Namaneliya", "Omara Negenahira", "Omara Batahira", "Pahalawaththa", "Pahala Obada", "Palle Julampitiya", "Pathegama", "Pissubedda", "Radaniara", "Rammala", "Saputhanthrikanda", "Thalapathkanda", "Udahagoda", "Uda Julampitiya", "Uthuru Haggithakanda", "Walasmulla Uthura", "Walasmulla Dakuna", "Walasmulla Negenahira", "Walasmulla Batahira", "Walasmulla Ihala", "Walasmulla Pahala", "Warapitiya", "Waththehengoda", "Weladagoda", "Widapola", "Widikanda", "Yahalmulla" }));
            jComboBox_marked1.setBorder(null);
            jComboBox_marked1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox_marked1ActionPerformed(evt);
                }
            });

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setTitle("View All Processing Records");
            setLocation(new java.awt.Point(200, 50));

            jPanel1.setBackground(new java.awt.Color(0, 51, 153));
            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true), "Raw, Marked and Applied records in Database", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
            jPanel1.setPreferredSize(new java.awt.Dimension(590, 400));

            jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "ID", "Name", "School", "Address", "Contact Number", "Birthday", "Marked or not", "QR"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false, false
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jTable1.setRowHeight(24);
            jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            jScrollPane2.setViewportView(jTable1);

            jPanel2.setBackground(new java.awt.Color(255, 255, 255));
            jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true), "Delete And Update"));

            jButton4.setBackground(new java.awt.Color(255, 153, 153));
            jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jButton4.setText("Delete All Data");
            jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });

            jButton3.setBackground(new java.awt.Color(255, 153, 153));
            jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jButton3.setText("Delete Selected");
            jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });

            jButton5.setBackground(new java.awt.Color(255, 153, 153));
            jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jButton5.setText("Update Selected");
            jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));
            jButton5.setPreferredSize(new java.awt.Dimension(89, 21));
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            jPanel4.setBackground(new java.awt.Color(255, 255, 255));

            jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel1.setText("Search by QR:");

            txtSearchBar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            txtSearchBar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtSearchBarActionPerformed(evt);
                }
            });

            btnSearch.setBackground(new java.awt.Color(255, 255, 255));
            btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ageregister/view/magnifying-glass3.png"))); // NOI18N
            btnSearch.setToolTipText("Search by QR");
            btnSearch.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSearchActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(txtSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))))
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(20, Short.MAX_VALUE))
            );

            jPanel5.setBackground(new java.awt.Color(255, 255, 255));

            jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel2.setText("Search marked records");

            jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel3.setText("by school :");

            jComboBox_marked.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jComboBox_marked.setMaximumRowCount(16);
            jComboBox_marked.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Unknown", "Sri Saddananda Piriwena Omara", "Walasmulla National School", "Warapitiya Secondary School", "Hadugala M.V", "Horewela M.V", "Kirama Dammananda M.V", "Medagamgoda M.V", "Omara M.V", "Egodabedda M.V", "Radaniara M.V", "Muruthawela M.V", "Pallejulampitiya M.V", "Kekiriobada M.V", "Vidikanda K.V", "Thalapathkanda K.V", "Keredeniya K.V", "Konkarahena K.V", "Bowala K.V", "Galwadiya K.V", "Agalabada K.V", "Bowala Vidyalaya" }));
            jComboBox_marked.setBorder(null);
            jComboBox_marked.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox_markedActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_marked, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(jComboBox_marked, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            jButton1.setBackground(new java.awt.Color(255, 255, 255));
            jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jButton1.setText("See Finalized Records");
            jButton1.setToolTipText("");
            jButton1.setBorder(null);
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButton6.setBackground(new java.awt.Color(255, 255, 255));
            jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jButton6.setText("See Stats");
            jButton6.setBorder(null);
            jButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, Short.MAX_VALUE))
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jScrollPane2)))
                    .addContainerGap())
            );

            jButton2.setBackground(new java.awt.Color(255, 255, 255));
            jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jButton2.setText("Close");
            jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jButton9.setBackground(new java.awt.Color(255, 255, 255));
            jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jButton9.setText("Add Data");
            jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
            jButton9.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton9ActionPerformed(evt);
                }
            });

            jLabel4.setBackground(new java.awt.Color(255, 255, 255));
            jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel4.setText("Search all by school:");

            jComboBox_all.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jComboBox_all.setMaximumRowCount(16);
            jComboBox_all.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Unknown", "Sri Saddananda Piriwena Omara", "Walasmulla National School", "Warapitiya Secondary School", "Hadugala M.V", "Horewela M.V", "Kirama Dammananda M.V", "Medagamgoda M.V", "Omara M.V", "Egodabedda M.V", "Radaniara M.V", "Muruthawela M.V", "Pallejulampitiya M.V", "Kekiriobada M.V", "Vidikanda K.V", "Thalapathkanda K.V", "Keredeniya K.V", "Konkarahena K.V", "Bowala K.V", "Galwadiya K.V", "Agalabada K.V", "Bowala Vidyalaya" }));
            jComboBox_all.setBorder(null);
            jComboBox_all.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox_allActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBox_all, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1232, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                    .addGap(15, 15, 15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jComboBox_all, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int id_val=(int)jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0);
        if(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 6).toString().equals("")){
             int response= JOptionPane.showConfirmDialog(this,"This record seems to be unmarked yet!.Do you want to delete it?","Are you sure?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(response==JOptionPane.YES_OPTION){
                db.deleteRow(id_val);
                m.setRowCount(0);
                fd.getData(m,this);
            }
            else if(response==JOptionPane.NO_OPTION){
                
        }
          
        }
        else{
              
            db.deleteRow(id_val);
            m.setRowCount(0);
            fd.getData(m,this);
       
        }
m_main.setRowCount(0);
ffd.getAndFilterData(new Date(), m_main);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
m_main.setRowCount(0);
ffd.getAndFilterData(new Date(), m_main);
this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
FinalizedDataHandler fdh=new FinalizedDataHandler();
String[] buttons = { "Cancel", "Only completed items", "All items" };
int rc = JOptionPane.showOptionDialog(null, "This database may contain both unmarked, marked,applied and finalized items and the deletion process can not be undone! What do you want to delete?", "Warning!",
JOptionPane.WARNING_MESSAGE, 0, null, buttons, buttons[2]);

 if(rc==0){
     
 }
 else{
//    ArrayList<Integer> list=new ArrayList<Integer>();
//    for(int i=0; i< jTable1.getModel().getRowCount();i++){
//        list.add(((Integer)jTable1.getModel().getValueAt(i, 0)));
//        
//    }
    if(rc==1){
//        fd.deleteBunchOfData(list, "DELETE FROM datatable WHERE ID=? AND flag=3");
        fdh.deleteAll();
        m.setRowCount(0);
        fd.getData(m,this);
        JOptionPane.showMessageDialog(this, "Sucessfully Deleted!");
        
    }
    else if(rc==2){
        fdh.deleteAll();
   //     fd.deleteBunchOfData(list, "DELETE FROM datatable WHERE ID=?");
        fd.deleteAll();
        m.setRowCount(0);
        fd.getData(m,this);
        JOptionPane.showMessageDialog(this, "Sucessfully Deleted!");
    }
     
 }
m_main.setRowCount(0);
ffd.getAndFilterData(new Date(), m_main);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 int id_val=(int)jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0);
 new UpdateData(fd.getDataById(id_val),id_val,m_main,m,this).setVisible(true);
 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        new AddData(m_main,m,this).setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if(!txtSearchBar.getText().equals("")){  
            try {
                fd.getSearchResultsOnQR(txtSearchBar.getText());
                txtSearchBar.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(ViewAll.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        

                
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchBarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FinalizedRecords fr=new FinalizedRecords(fdh);
        fr.setVisible(true);
        fdh.getData((DefaultTableModel)fr.finalizedTable.getModel());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      new Statistics().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox_markedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_markedActionPerformed
       if(!(jComboBox_marked.getSelectedIndex()==0)){
            try {
                fd.getSearchResultsOnGN(jComboBox_marked.getSelectedItem().toString());
                
                
            } catch (SQLException ex) {
                Logger.getLogger(ViewAll.class.getName()).log(Level.SEVERE, null, ex);
            }   
       }
    }//GEN-LAST:event_jComboBox_markedActionPerformed

    private void jComboBox_marked1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_marked1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_marked1ActionPerformed

    private void jComboBox_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_allActionPerformed
      if(!(jComboBox_all.getSelectedIndex()==0)){
            try {
                new FetchData(m_main,m,ffd,this).getAllSearchResultsOnGN(jComboBox_all.getSelectedItem().toString());
                jComboBox_all.setSelectedIndex(0);
                
            } catch (SQLException ex) {
                Logger.getLogger(ViewAll.class.getName()).log(Level.SEVERE, null, ex);
            }   
      }
    }//GEN-LAST:event_jComboBox_allActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    public javax.swing.JComboBox<String> jComboBox_all;
    public javax.swing.JComboBox<String> jComboBox_marked;
    public javax.swing.JComboBox<String> jComboBox_marked1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextField txtSearchBar;
    // End of variables declaration//GEN-END:variables
}
